# "samples.tsv" tab-delimited, must contains columns: 'sample','condition','R1', 'R2'
# in case of single-end, leave 'R2' empty.

samples: "sample.tsv"

params:
    threads: 16

fastqc:
    fastq_dir: "fastq/"
    out_dir: "fastqc/"

align:
    reference: "genome"
    gtf: "gencode.vM25.primary_assembly.annotation.gtf"
    star_path: "/star/2.7.3a/bin/"
    # only required for single end library
    fragment_len_sd: 80
    fragment_len_mean: 210
    # required if genome index 'reference' is empty
    genome_fasta: "GRCm38.primary_assembly.genome.fa"
    # read_length - 1
    star_sjdboverhang: 50

diffexp:
    adjusted_pvalue: 0.05
    # whether or not to output rnk files intend to be used for gsea analysis.
    rnk: "true"

gsea:
  # gsea presume human genes, so use with caution
  exe_jar: "resource/gsea-3.0.jar"
  gmt: "resource/c2.cp.v7.0.symbols.gmt"
  no_perm: 1000
  no_plot: 20
  set_max: 800
  set_min: 15
  seed: 521
